import ast

QSFP_DATA_MAP = {
    'model': 'Vendor PN',
    'vendor_oui': 'Vendor OUI',
    'vendor_date': 'Vendor Date Code(YYYY-MM-DD Lot)',
    'manufacturer': 'Vendor Name',
    'vendor_rev': 'Vendor Rev',
    'serial': 'Vendor SN',
    'type': 'Identifier',
    'ext_identifier': 'Extended Identifier',
    'ext_rateselect_compliance': 'Extended RateSelect Compliance',
    'cable_length': 'cable_length',
    'cable_type': 'Length',
    'nominal_bit_rate': 'Nominal Bit Rate(100Mbs)',
    'specification_compliance': 'Specification compliance',
    'encoding': 'Encoding',
    'connector': 'Connector',
    'application_advertisement': 'Application Advertisement'
}

QSFP_CMIS_DELTA_DATA_MAP = {
    'host_lane_count': 'Host Lane Count',
    'media_lane_count': 'Media Lane Count',
    'active_apsel_hostlane1': 'Active application selected code assigned to host lane 1',
    'active_apsel_hostlane2': 'Active application selected code assigned to host lane 2',
    'active_apsel_hostlane3': 'Active application selected code assigned to host lane 3',
    'active_apsel_hostlane4': 'Active application selected code assigned to host lane 4',
    'active_apsel_hostlane5': 'Active application selected code assigned to host lane 5',
    'active_apsel_hostlane6': 'Active application selected code assigned to host lane 6',
    'active_apsel_hostlane7': 'Active application selected code assigned to host lane 7',
    'active_apsel_hostlane8': 'Active application selected code assigned to host lane 8',
    'media_interface_technology': 'Media Interface Technology',
    'hardware_rev': 'Module Hardware Rev',
    'cmis_rev': 'CMIS Rev',
    'active_firmware': 'Active Firmware',
    'inactive_firmware': 'Inactive Firmware',
    'supported_max_tx_power': 'Supported Max TX Power',
    'supported_min_tx_power': 'Supported Min TX Power',
    'supported_max_laser_freq': 'Supported Max Laser Frequency',
    'supported_min_laser_freq': 'Supported Min Laser Frequency'
}

CMIS_DATA_MAP = {**QSFP_DATA_MAP, **QSFP_CMIS_DELTA_DATA_MAP}

# Common fileds for all types:
# For non-CMIS, only first 1 or 4 lanes are applicable.
# For CMIS, all 8 lanes are applicable.
QSFP_STATUS_MAP = {
    'cmis_state': 'CMIS State (SW)',
    'txfault1': 'Tx fault flag on media lane 1',
    'txfault2': 'Tx fault flag on media lane 2',
    'txfault3': 'Tx fault flag on media lane 3',
    'txfault4': 'Tx fault flag on media lane 4',
    'txfault5': 'Tx fault flag on media lane 5',
    'txfault6': 'Tx fault flag on media lane 6',
    'txfault7': 'Tx fault flag on media lane 7',
    'txfault8': 'Tx fault flag on media lane 8',
    'rxlos1': 'Rx loss of signal flag on media lane 1',
    'rxlos2': 'Rx loss of signal flag on media lane 2',
    'rxlos3': 'Rx loss of signal flag on media lane 3',
    'rxlos4': 'Rx loss of signal flag on media lane 4',
    'rxlos5': 'Rx loss of signal flag on media lane 5',
    'rxlos6': 'Rx loss of signal flag on media lane 6',
    'rxlos7': 'Rx loss of signal flag on media lane 7',
    'rxlos8': 'Rx loss of signal flag on media lane 8',
    'tx1disable': 'TX disable status on lane 1',
    'tx2disable': 'TX disable status on lane 2',
    'tx3disable': 'TX disable status on lane 3',
    'tx4disable': 'TX disable status on lane 4',
    'tx5disable': 'TX disable status on lane 5',
    'tx6disable': 'TX disable status on lane 6',
    'tx7disable': 'TX disable status on lane 7',
    'tx8disable': 'TX disable status on lane 8',
    'tx_disabled_channel': 'Disabled TX channels'
}

# CMIS specific fields (excluding C-CMIS specific):
CMIS_STATUS_MAP = {
    'module_state': 'Current module state',
    'module_fault_cause': 'Reason of entering the module fault state',
    'datapath_firmware_fault': 'Datapath firmware fault',
    'module_firmware_fault': 'Module firmware fault',
    'module_state_changed': 'Module state changed',
    'DP1State': 'Data path state indicator on host lane 1',
    'DP2State': 'Data path state indicator on host lane 2',
    'DP3State': 'Data path state indicator on host lane 3',
    'DP4State': 'Data path state indicator on host lane 4',
    'DP5State': 'Data path state indicator on host lane 5',
    'DP6State': 'Data path state indicator on host lane 6',
    'DP7State': 'Data path state indicator on host lane 7',
    'DP8State': 'Data path state indicator on host lane 8',
    'txoutput_status1': 'Tx output status on media lane 1',
    'txoutput_status2': 'Tx output status on media lane 2',
    'txoutput_status3': 'Tx output status on media lane 3',
    'txoutput_status4': 'Tx output status on media lane 4',
    'txoutput_status5': 'Tx output status on media lane 5',
    'txoutput_status6': 'Tx output status on media lane 6',
    'txoutput_status7': 'Tx output status on media lane 7',
    'txoutput_status8': 'Tx output status on media lane 8',
    'rxoutput_status_hostlane1': 'Rx output status on host lane 1',
    'rxoutput_status_hostlane2': 'Rx output status on host lane 2',
    'rxoutput_status_hostlane3': 'Rx output status on host lane 3',
    'rxoutput_status_hostlane4': 'Rx output status on host lane 4',
    'rxoutput_status_hostlane5': 'Rx output status on host lane 5',
    'rxoutput_status_hostlane6': 'Rx output status on host lane 6',
    'rxoutput_status_hostlane7': 'Rx output status on host lane 7',
    'rxoutput_status_hostlane8': 'Rx output status on host lane 8',
    'txlos_hostlane1': 'Tx loss of signal flag on host lane 1',
    'txlos_hostlane2': 'Tx loss of signal flag on host lane 2',
    'txlos_hostlane3': 'Tx loss of signal flag on host lane 3',
    'txlos_hostlane4': 'Tx loss of signal flag on host lane 4',
    'txlos_hostlane5': 'Tx loss of signal flag on host lane 5',
    'txlos_hostlane6': 'Tx loss of signal flag on host lane 6',
    'txlos_hostlane7': 'Tx loss of signal flag on host lane 7',
    'txlos_hostlane8': 'Tx loss of signal flag on host lane 8',
    'txcdrlol_hostlane1': 'Tx clock and data recovery loss of lock on host lane 1',
    'txcdrlol_hostlane2': 'Tx clock and data recovery loss of lock on host lane 2',
    'txcdrlol_hostlane3': 'Tx clock and data recovery loss of lock on host lane 3',
    'txcdrlol_hostlane4': 'Tx clock and data recovery loss of lock on host lane 4',
    'txcdrlol_hostlane5': 'Tx clock and data recovery loss of lock on host lane 5',
    'txcdrlol_hostlane6': 'Tx clock and data recovery loss of lock on host lane 6',
    'txcdrlol_hostlane7': 'Tx clock and data recovery loss of lock on host lane 7',
    'txcdrlol_hostlane8': 'Tx clock and data recovery loss of lock on host lane 8',
    'rxcdrlol1': 'Rx clock and data recovery loss of lock on media lane 1',
    'rxcdrlol2': 'Rx clock and data recovery loss of lock on media lane 2',
    'rxcdrlol3': 'Rx clock and data recovery loss of lock on media lane 3',
    'rxcdrlol4': 'Rx clock and data recovery loss of lock on media lane 4',
    'rxcdrlol5': 'Rx clock and data recovery loss of lock on media lane 5',
    'rxcdrlol6': 'Rx clock and data recovery loss of lock on media lane 6',
    'rxcdrlol7': 'Rx clock and data recovery loss of lock on media lane 7',
    'rxcdrlol8': 'Rx clock and data recovery loss of lock on media lane 8',
    'config_state_hostlane1': 'Configuration status for the data path of host line 1',
    'config_state_hostlane2': 'Configuration status for the data path of host line 2',
    'config_state_hostlane3': 'Configuration status for the data path of host line 3',
    'config_state_hostlane4': 'Configuration status for the data path of host line 4',
    'config_state_hostlane5': 'Configuration status for the data path of host line 5',
    'config_state_hostlane6': 'Configuration status for the data path of host line 6',
    'config_state_hostlane7': 'Configuration status for the data path of host line 7',
    'config_state_hostlane8': 'Configuration status for the data path of host line 8',
    'dpinit_pending_hostlane1': 'Data path configuration updated on host lane 1',
    'dpinit_pending_hostlane2': 'Data path configuration updated on host lane 2',
    'dpinit_pending_hostlane3': 'Data path configuration updated on host lane 3',
    'dpinit_pending_hostlane4': 'Data path configuration updated on host lane 4',
    'dpinit_pending_hostlane5': 'Data path configuration updated on host lane 5',
    'dpinit_pending_hostlane6': 'Data path configuration updated on host lane 6',
    'dpinit_pending_hostlane7': 'Data path configuration updated on host lane 7',
    'dpinit_pending_hostlane8': 'Data path configuration updated on host lane 8',
    'temphighalarm_flag': 'Temperature high alarm flag',
    'temphighwarning_flag': 'Temperature high warning flag',
    'templowwarning_flag': 'Temperature low warning flag',
    'templowalarm_flag': 'Temperature low alarm flag',
    'vcchighalarm_flag': 'Vcc high alarm flag',
    'vcchighwarning_flag': 'Vcc high warning flag',
    'vcclowwarning_flag': 'Vcc low warning flag',
    'vcclowalarm_flag': 'Vcc low alarm flag',
    'txpowerhighalarm_flag1': 'Tx power high alarm flag on lane 1',
    'txpowerhighalarm_flag2': 'Tx power high alarm flag on lane 2',
    'txpowerhighalarm_flag3': 'Tx power high alarm flag on lane 3',
    'txpowerhighalarm_flag4': 'Tx power high alarm flag on lane 4',
    'txpowerhighalarm_flag5': 'Tx power high alarm flag on lane 5',
    'txpowerhighalarm_flag6': 'Tx power high alarm flag on lane 6',
    'txpowerhighalarm_flag7': 'Tx power high alarm flag on lane 7',
    'txpowerhighalarm_flag8': 'Tx power high alarm flag on lane 8',
    'txpowerhighwarning_flag1': 'Tx power high warning flag on lane 1',
    'txpowerhighwarning_flag2': 'Tx power high warning flag on lane 2',
    'txpowerhighwarning_flag3': 'Tx power high warning flag on lane 3',
    'txpowerhighwarning_flag4': 'Tx power high warning flag on lane 4',
    'txpowerhighwarning_flag5': 'Tx power high warning flag on lane 5',
    'txpowerhighwarning_flag6': 'Tx power high warning flag on lane 6',
    'txpowerhighwarning_flag7': 'Tx power high warning flag on lane 7',
    'txpowerhighwarning_flag8': 'Tx power high warning flag on lane 8',
    'txpowerlowwarning_flag1': 'Tx power low warning flag on lane 1',
    'txpowerlowwarning_flag2': 'Tx power low warning flag on lane 2',
    'txpowerlowwarning_flag3': 'Tx power low warning flag on lane 3',
    'txpowerlowwarning_flag4': 'Tx power low warning flag on lane 4',
    'txpowerlowwarning_flag5': 'Tx power low warning flag on lane 5',
    'txpowerlowwarning_flag6': 'Tx power low warning flag on lane 6',
    'txpowerlowwarning_flag7': 'Tx power low warning flag on lane 7',
    'txpowerlowwarning_flag8': 'Tx power low warning flag on lane 8',
    'txpowerlowalarm_flag1': 'Tx power low alarm flag on lane 1',
    'txpowerlowalarm_flag2': 'Tx power low alarm flag on lane 2',
    'txpowerlowalarm_flag3': 'Tx power low alarm flag on lane 3',
    'txpowerlowalarm_flag4': 'Tx power low alarm flag on lane 4',
    'txpowerlowalarm_flag5': 'Tx power low alarm flag on lane 5',
    'txpowerlowalarm_flag6': 'Tx power low alarm flag on lane 6',
    'txpowerlowalarm_flag7': 'Tx power low alarm flag on lane 7',
    'txpowerlowalarm_flag8': 'Tx power low alarm flag on lane 8',
    'rxpowerhighalarm_flag1': 'Rx power high alarm flag on lane 1',
    'rxpowerhighalarm_flag2': 'Rx power high alarm flag on lane 2',
    'rxpowerhighalarm_flag3': 'Rx power high alarm flag on lane 3',
    'rxpowerhighalarm_flag4': 'Rx power high alarm flag on lane 4',
    'rxpowerhighalarm_flag5': 'Rx power high alarm flag on lane 5',
    'rxpowerhighalarm_flag6': 'Rx power high alarm flag on lane 6',
    'rxpowerhighalarm_flag7': 'Rx power high alarm flag on lane 7',
    'rxpowerhighalarm_flag8': 'Rx power high alarm flag on lane 8',
    'rxpowerhighwarning_flag1': 'Rx power high warning flag on lane 1',
    'rxpowerhighwarning_flag2': 'Rx power high warning flag on lane 2',
    'rxpowerhighwarning_flag3': 'Rx power high warning flag on lane 3',
    'rxpowerhighwarning_flag4': 'Rx power high warning flag on lane 4',
    'rxpowerhighwarning_flag5': 'Rx power high warning flag on lane 5',
    'rxpowerhighwarning_flag6': 'Rx power high warning flag on lane 6',
    'rxpowerhighwarning_flag7': 'Rx power high warning flag on lane 7',
    'rxpowerhighwarning_flag8': 'Rx power high warning flag on lane 8',
    'rxpowerlowwarning_flag1': 'Rx power low warning flag on lane 1',
    'rxpowerlowwarning_flag2': 'Rx power low warning flag on lane 2',
    'rxpowerlowwarning_flag3': 'Rx power low warning flag on lane 3',
    'rxpowerlowwarning_flag4': 'Rx power low warning flag on lane 4',
    'rxpowerlowwarning_flag5': 'Rx power low warning flag on lane 5',
    'rxpowerlowwarning_flag6': 'Rx power low warning flag on lane 6',
    'rxpowerlowwarning_flag7': 'Rx power low warning flag on lane 7',
    'rxpowerlowwarning_flag8': 'Rx power low warning flag on lane 8',
    'rxpowerlowalarm_flag1': 'Rx power low alarm flag on lane 1',
    'rxpowerlowalarm_flag2': 'Rx power low alarm flag on lane 2',
    'rxpowerlowalarm_flag3': 'Rx power low alarm flag on lane 3',
    'rxpowerlowalarm_flag4': 'Rx power low alarm flag on lane 4',
    'rxpowerlowalarm_flag5': 'Rx power low alarm flag on lane 5',
    'rxpowerlowalarm_flag6': 'Rx power low alarm flag on lane 6',
    'rxpowerlowalarm_flag7': 'Rx power low alarm flag on lane 7',
    'rxpowerlowalarm_flag8': 'Rx power low alarm flag on lane 8',
    'txbiashighalarm_flag1': 'Tx bias high alarm flag on lane 1',
    'txbiashighalarm_flag2': 'Tx bias high alarm flag on lane 2',
    'txbiashighalarm_flag3': 'Tx bias high alarm flag on lane 3',
    'txbiashighalarm_flag4': 'Tx bias high alarm flag on lane 4',
    'txbiashighalarm_flag5': 'Tx bias high alarm flag on lane 5',
    'txbiashighalarm_flag6': 'Tx bias high alarm flag on lane 6',
    'txbiashighalarm_flag7': 'Tx bias high alarm flag on lane 7',
    'txbiashighalarm_flag8': 'Tx bias high alarm flag on lane 8',
    'txbiashighwarning_flag1': 'Tx bias high warning flag on lane 1',
    'txbiashighwarning_flag2': 'Tx bias high warning flag on lane 2',
    'txbiashighwarning_flag3': 'Tx bias high warning flag on lane 3',
    'txbiashighwarning_flag4': 'Tx bias high warning flag on lane 4',
    'txbiashighwarning_flag5': 'Tx bias high warning flag on lane 5',
    'txbiashighwarning_flag6': 'Tx bias high warning flag on lane 6',
    'txbiashighwarning_flag7': 'Tx bias high warning flag on lane 7',
    'txbiashighwarning_flag8': 'Tx bias high warning flag on lane 8',
    'txbiaslowwarning_flag1': 'Tx bias low warning flag on lane 1',
    'txbiaslowwarning_flag2': 'Tx bias low warning flag on lane 2',
    'txbiaslowwarning_flag3': 'Tx bias low warning flag on lane 3',
    'txbiaslowwarning_flag4': 'Tx bias low warning flag on lane 4',
    'txbiaslowwarning_flag5': 'Tx bias low warning flag on lane 5',
    'txbiaslowwarning_flag6': 'Tx bias low warning flag on lane 6',
    'txbiaslowwarning_flag7': 'Tx bias low warning flag on lane 7',
    'txbiaslowwarning_flag8': 'Tx bias low warning flag on lane 8',
    'txbiaslowalarm_flag1': 'Tx bias low alarm flag on lane 1',
    'txbiaslowalarm_flag2': 'Tx bias low alarm flag on lane 2',
    'txbiaslowalarm_flag3': 'Tx bias low alarm flag on lane 3',
    'txbiaslowalarm_flag4': 'Tx bias low alarm flag on lane 4',
    'txbiaslowalarm_flag5': 'Tx bias low alarm flag on lane 5',
    'txbiaslowalarm_flag6': 'Tx bias low alarm flag on lane 6',
    'txbiaslowalarm_flag7': 'Tx bias low alarm flag on lane 7',
    'txbiaslowalarm_flag8': 'Tx bias low alarm flag on lane 8',
    'lasertemphighalarm_flag': 'Laser temperature high alarm flag',
    'lasertemphighwarning_flag': 'Laser temperature high warning flag',
    'lasertemplowwarning_flag': 'Laser temperature low warning flag',
    'lasertemplowalarm_flag': 'Laser temperature low alarm flag',
    'prefecberhighalarm_flag': 'Prefec ber high alarm flag',
    'prefecberhighwarning_flag': 'Prefec ber high warning flag',
    'prefecberlowwarning_flag': 'Prefec ber low warning flag',
    'prefecberlowalarm_flag': 'Prefec ber low alarm flag',
    'postfecberhighalarm_flag': 'Postfec ber high alarm flag',
    'postfecberhighwarning_flag': 'Postfec ber high warning flag',
    'postfecberlowwarning_flag': 'Postfec ber low warning flag',
    'postfecberlowalarm_flag': 'Postfec ber low alarm flag'
}

# C-CMIS specific fields:
CCMIS_STATUS_MAP = {
    'tuning_in_progress': 'Tuning in progress status',
    'wavelength_unlock_status': 'Laser unlocked status',
    'target_output_power_oor': 'Target output power out of range flag',
    'fine_tuning_oor': 'Fine tuning out of range flag',
    'tuning_not_accepted': 'Tuning not accepted flag',
    'invalid_channel_num': 'Invalid channel number flag',
    'tuning_complete': 'Tuning complete flag',
    'biasxihighalarm_flag': 'Bias xi high alarm flag',
    'biasxihighwarning_flag': 'Bias xi high warning flag',
    'biasxilowwarning_flag': 'Bias xi low warning flag',
    'biasxilowalarm_flag': 'Bias xi low alarm flag',
    'biasxqhighalarm_flag': 'Bias xq high alarm flag',
    'biasxqhighwarning_flag': 'Bias xq high warning flag',
    'biasxqlowwarning_flag': 'Bias xq low warning flag',
    'biasxqlowalarm_flag': 'Bias xq low alarm flag',
    'biasxphighalarm_flag': 'Bias xp high alarm flag',
    'biasxphighwarning_flag': 'Bias xp high warning flag',
    'biasxplowwarning_flag': 'Bias xp low warning flag',
    'biasxplowalarm_flag': 'Bias xp low alarm flag',
    'biasyihighalarm_flag': 'Bias yi high alarm flag',
    'biasyihighwarning_flag': 'Bias yi high warning flag',
    'biasyilowwarning_flag': 'Bias yi low warning flag',
    'biasyilowalarm_flag': 'Bias yi low alarm flag',
    'biasyqhighalarm_flag': 'Bias yq high alarm flag',
    'biasyqhighwarning_flag': 'Bias yq high warning flag',
    'biasyqlowwarning_flag': 'Bias yq low warning flag',
    'biasyqlowalarm_flag': 'Bias yq low alarm flag',
    'biasyphighalarm_flag': 'Bias yp high alarm flag',
    'biasyphighwarning_flag': 'Bias yp high warning flag',
    'biasyplowwarning_flag': 'Bias yp low warning flag',
    'biasyplowalarm_flag': 'Bias yp low alarm flag',
    'cdshorthighalarm_flag': 'CD short high alarm flag',
    'cdshorthighwarning_flag': 'CD short high warning flag',
    'cdshortlowwarning_flag': 'CD short low warning flag',
    'cdshortlowalarm_flag': 'CD short low alarm flag',
    'cdlonghighalarm_flag': 'CD long high alarm flag',
    'cdlonghighwarning_flag': 'CD long high warning flag',
    'cdlonglowwarning_flag': 'CD long low warning flag',
    'cdlonglowalarm_flag': 'CD long low alarm flag',
    'dgdhighalarm_flag': 'DGD high alarm flag',
    'dgdhighwarning_flag': 'DGD high warning flag',
    'dgdlowwarning_flag': 'DGD low warning flag',
    'dgdlowalarm_flag': 'DGD low alarm flag',
    'sopmdhighalarm_flag': 'SOPMD high alarm flag',
    'sopmdhighwarning_flag': 'SOPMD high warning flag',
    'sopmdlowwarning_flag': 'SOPMD low warning flag',
    'sopmdlowalarm_flag': 'SOPMD low alarm flag',
    'pdlhighalarm_flag': 'PDL high alarm flag',
    'pdlhighwarning_flag': 'PDL high warning flag',
    'pdllowwarning_flag': 'PDL low warning flag',
    'pdllowalarm_flag': 'PDL low alarm flag',
    'osnrhighalarm_flag': 'OSNR high alarm flag',
    'osnrhighwarning_flag': 'OSNR high warning flag',
    'osnrlowwarning_flag': 'OSNR low warning flag',
    'osnrlowalarm_flag': 'OSNR low alarm flag',
    'esnrhighalarm_flag': 'ESNR high alarm flag',
    'esnrhighwarning_flag': 'ESNR high warning flag',
    'esnrlowwarning_flag': 'ESNR low warning flag',
    'esnrlowalarm_flag': 'ESNR low alarm flag',
    'cfohighalarm_flag': 'CFO high alarm flag',
    'cfohighwarning_flag': 'CFO high warning flag',
    'cfolowwarning_flag': 'CFO low warning flag',
    'cfolowalarm_flag': 'CFO low alarm flag',
    'txcurrpowerhighalarm_flag': 'Txcurrpower high alarm flag',
    'txcurrpowerhighwarning_flag': 'Txcurrpower high warning flag',
    'txcurrpowerlowwarning_flag': 'Txcurrpower low warning flag',
    'txcurrpowerlowalarm_flag': 'Txcurrpower low alarm flag',
    'rxtotpowerhighalarm_flag': 'Rxtotpower high alarm flag',
    'rxtotpowerhighwarning_flag': 'Rxtotpower high warning flag',
    'rxtotpowerlowwarning_flag': 'Rxtotpower low warning flag',
    'rxtotpowerlowalarm_flag': 'Rxtotpower low alarm flag',
    'rxsigpowerhighalarm_flag': 'Rxsigpower high alarm flag',
    'rxsigpowerhighwarning_flag': 'Rxsigpower high warning flag',
    'rxsigpowerlowwarning_flag': 'Rxsigpower low warning flag',
    'rxsigpowerlowalarm_flag': 'Rxsigpower low alarm flag'
}

def covert_application_advertisement_to_output_string(indent, sfp_info_dict):
    key = 'application_advertisement'
    field_name = '{}{}: '.format(indent, QSFP_DATA_MAP[key])
    output = field_name
    try:
        app_adv_str = sfp_info_dict[key]
        app_adv_dict = ast.literal_eval(app_adv_str)
        if not app_adv_dict:
            output += 'N/A\n'
        else:
            lines = []
            for item in app_adv_dict.values():
                host_interface_id = item.get('host_electrical_interface_id')
                if not host_interface_id:
                    continue
                elements = []
                elements.append(host_interface_id)
                host_assign_options = item.get('host_lane_assignment_options')
                host_assign_options = hex(host_assign_options) if host_assign_options else 'Unknown'
                elements.append(f'Host Assign ({host_assign_options})')
                elements.append(item.get('module_media_interface_id', 'Unknown'))
                media_assign_options = item.get('media_lane_assignment_options')
                media_assign_options = hex(media_assign_options) if media_assign_options else 'Unknown'
                elements.append(f'Media Assign ({media_assign_options})')
                lines.append(' - '.join(elements))
            sep = '\n' + ' ' * len(field_name)
            output += sep.join(lines)
            output += '\n'
    except Exception:
        output += '{}\n'.format(app_adv_str)
    return output
