#!/usr/bin/env python3

import sys
from io import StringIO

from portconfig import get_port_config
from sonic_py_common import device_info


def translate_line(line, ports):
    allowed_symbols = ['-', '_']
    sb = StringIO()
    start = 0
    end = 0
    while end < len(line):
        if line[end].isalnum() or line[end] in allowed_symbols:
            pass
        else: 
            # End of a word
            word = line[start:end]
            if word in ports:
                sb.write(ports[word]['alias'])
            else:
                sb.write(word)
            sb.write(line[end])
            start = end + 1
        end += 1
    if start != len(line):
        word = line[start:]
        if word in ports:
            sb.write(ports[word]['alias'])
        else:
            sb.write(word)
    return sb.getvalue()

def main():
    (platform, hwsku) = device_info.get_platform_and_hwsku()
    (ports, _) = get_port_config(hwsku, platform)
    for line in sys.stdin:
        sys.stdout.write(translate_line(line, ports))

if __name__ == "__main__":
    main()
