#! /bin/bash

# Check root privileges
if [[ "$EUID" -ne 0 ]]
then
  echo "Please run as root" >&2
  exit 1
fi

function stop_sonic_services()
{
    echo "Stopping syncd..."
    docker exec -i syncd /usr/bin/syncd_request_shutdown --cold > /dev/null
    sleep 3
}

# Obtain our platform as we will mount directories with these names in each docker
PLATFORM=`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`

DEVPATH="/usr/share/sonic/device"
REBOOT="platform_reboot"

# Stop syncd gracefully.
stop_sonic_services

if [ -x ${DEVPATH}/${PLATFORM}/${REBOOT} ]; then
    sync
    sleep 3
    echo "Rebooting with platform ${PLATFORM} specific tool ..."
    ${DEVPATH}/${PLATFORM}/${REBOOT}
    exit 0
fi

/sbin/reboot $@
